### ISSUE TITLE
Getting Started -> Issuing a digital asset

### ISSUE THREAD

**Issue by RogerFelipeNsk** [DigiByte-Core/DigiAssets-Protocol-Specifications#1]
`{ Error
    at DigiAssetBuilder.buildIssueTransaction (C:\xamppPHP7\htdocs\digiid\node_modules\digiasset-transaction-builder\index.js:58:11)
    at C:\xamppPHP7\htdocs\digiid\node_modules\digiassets-sdk\src\digiassets.js:123:23
    at C:\xamppPHP7\htdocs\digiid\node_modules\digiassets-sdk\lib\metadata_server.js:50:14
    at ConnectManager.handleResponse (C:\xamppPHP7\htdocs\digiid\node_modules\node-rest-client\lib\node-rest-client.js:452:5)
    at ConnectManager.handleEnd (C:\xamppPHP7\htdocs\digiid\node_modules\node-rest-client\lib\node-rest-client.js:422:10)
    at IncomingMessage.<anonymous> (C:\xamppPHP7\htdocs\digiid\node_modules\node-rest-client\lib\node-rest-client.js:591:13)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  explanation: undefined,
  response: undefined,
  code: 20003,
  status: 500,
  name: 'NotEnoughFundsError',
  message: 'Not enough satoshi to cover transaction',
  type: 'issue' }`

**Comment by ChillingSilence** [comment]
Have you added some testnet DigiByte? You can get some from https://testnet-1.us.digibyteservers.io

**Comment by LeberTecnologia** [comment]
> Have you added some testnet DigiByte? You can get some from https://testnet-1.us.digibyteservers.io


**first I run the index.js to know the address, but the error returned was the above, and should be the one below:**

`{ explanation: 'address mzjtnyfYxZYL9nVzmdn5eBJyD18M8joUhS does not have any unused outputs',
  code: 20003,
  status: 500,
  name: 'NotEnoughFundsError',
  message: 'Not enough satoshi to cover transaction',
  type: 'issuance' }
`

then I ran the file with some money, I was able to create the asset but I got the following error:
`TypeError: Right-hand side of 'instanceof' is not an object
    at errorHandler (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-errors/lib/errorHandler.js:21:13)
    at Layer.handle_error (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:315:13)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:315:13)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:275:10)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/express-winston/index.js:139:9
    at Layer.handle_error (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:315:13)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:315:13)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:275:10)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:635:15
    at
next (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/index.js:260:14)
    at next (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/express/lib/router/route.js:127:14)
    at /home/ubuntu/DigiAssets-Block-Explorer/app/controllers/api.js:1262:21
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/scanner.js:1745:23
    at end (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/scanner.js:1657:5)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/scanner.js:1711:14
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/node_modules/async/lib/async.js:52:16
    at Object.callback (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/node_modules/async/lib/async.js:1209:30)
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/node_modules/async/lib/async.js:906:35
    at _arrayEach (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/node_modules/async/lib/async.js:85:13)

   at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/node_modules/async/lib/async.js:898:17
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/DigiAssets-Block-Explorer/node_modules/digiasset-block-parser/scanner.js:1405:16
    at cb (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/bitcoin-async/lib/index.js:33:63)
    at tryCatcher (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/casimircore/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/casimircore/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/DigiAssets-Block-Explorer/node_modules/casimircore/node_modules/bluebird/js/release/promise.js:569:18)`
